export const artisticThemes = {
	arctic_frost: {
		name: "Arctic Frost",
		description: "Pale blues and crisp whites for a frozen landscape look",
		bg: "#F0F9FF",
		text: "#0C4A6E",
		water: "#BAE6FD",
		parks: "#E0F2FE",
		road_motorway: "#0EA5E9",
		road_primary: "#38BDF8",
		road_secondary: "#7DD3FC",
		road_tertiary: "#BAE6FD",
		road_residential: "#E0F2FE",
		road_default: "#7DD3FC"
	},
	volcanic_ash: {
		name: "Volcanic Ash",
		description: "Deep charcoal and glowing embers - high drama style",
		bg: "#1C1917",
		text: "#FAFAF9",
		water: "#0C0A09",
		parks: "#292524",
		road_motorway: "#EF4444",
		road_primary: "#F87171",
		road_secondary: "#B91C1C",
		road_tertiary: "#7F1D1D",
		road_residential: "#450A0A",
		road_default: "#B91C1C"
	},
	emerald_valley: {
		name: "Emerald Valley",
		description: "Lush mossy greens and deep forest tones",
		bg: "#022C22",
		text: "#D1FAE5",
		water: "#064E3B",
		parks: "#065F46",
		road_motorway: "#10B981",
		road_primary: "#34D399",
		road_secondary: "#059669",
		road_tertiary: "#047857",
		road_residential: "#064E3B",
		road_default: "#059669"
	},
	golden_era: {
		name: "Golden Era",
		description: "Rich yellows and deep browns recalling classic cartography",
		bg: "#FEFCE8",
		text: "#713F12",
		water: "#FEF08A",
		parks: "#FDE047",
		road_motorway: "#854D0E",
		road_primary: "#A16207",
		road_secondary: "#CA8A04",
		road_tertiary: "#EAB308",
		road_residential: "#FACC15",
		road_default: "#CA8A04"
	},
	cyber_glitch: {
		name: "Cyber Glitch",
		description: "Electric purples and neon yellows for a digital future",
		bg: "#2E1065",
		text: "#F0ABFC",
		water: "#4C1D95",
		parks: "#581C87",
		road_motorway: "#FACC15",
		road_primary: "#EAB308",
		road_secondary: "#A855F7",
		road_tertiary: "#C084FC",
		road_residential: "#D8B4FE",
		road_default: "#A855F7"
	},
	rustic_clay: {
		name: "Rustic Clay",
		description: "Earthy reds and warm oranges - sun-baked urban style",
		bg: "#FFF7ED",
		text: "#7C2D12",
		water: "#FFEDD5",
		parks: "#FED7AA",
		road_motorway: "#9A3412",
		road_primary: "#C2410C",
		road_secondary: "#EA580C",
		road_tertiary: "#F97316",
		road_residential: "#FB923C",
		road_default: "#EA580C"
	},
	deep_ocean: {
		name: "Deep Ocean",
		description: "Dark navy depths and teal currents",
		bg: "#082F49",
		text: "#E0F2FE",
		water: "#0C4A6E",
		parks: "#075985",
		road_motorway: "#0EA5E9",
		road_primary: "#38BDF8",
		road_secondary: "#7DD3FC",
		road_tertiary: "#BAE6FD",
		road_residential: "#0C4A6E",
		road_default: "#38BDF8"
	},
	monochrome_pro: {
		name: "Monochrome Pro",
		description: "Balanced greyscale for professional architectural maps",
		bg: "#FFFFFF",
		text: "#18181B",
		water: "#F4F4F5",
		parks: "#E4E4E7",
		road_motorway: "#18181B",
		road_primary: "#3F3F46",
		road_secondary: "#52525B",
		road_tertiary: "#71717A",
		road_residential: "#A1A1AA",
		road_default: "#52525B"
	},
	lavender_mist: {
		name: "Lavender Mist",
		description: "Soft purples and muted greys - dreamy cartography",
		bg: "#F5F3FF",
		text: "#4C1D95",
		water: "#EDE9FE",
		parks: "#DDD6FE",
		road_motorway: "#5B21B6",
		road_primary: "#6D28D9",
		road_secondary: "#7C3AED",
		road_tertiary: "#8B5CF6",
		road_residential: "#A78BFA",
		road_default: "#7C3AED"
	},
	autumn_whisper: {
		name: "Autumn Whisper",
		description: "Burned oranges and deep ochre tints of fallen leaves",
		bg: "#451A03",
		text: "#FEF3C7",
		water: "#78350F",
		parks: "#92400E",
		road_motorway: "#F59E0B",
		road_primary: "#FBBF24",
		road_secondary: "#FCD34D",
		road_tertiary: "#FDE68A",
		road_residential: "#FEF3C7",
		road_default: "#FBBF24"
	}
};
